### ISSUE TITLE
Module ply.lex not found using Singularity

### ISSUE THREAD

**Issue by VLoegler** [EichlerLab/pav#25]
Hi, 

While running pav, a few jobs end up with an error because the module ply.lex is not found. I'm attaching the log file, and here is an example of error:

Error in rule call_lg_discover:
    jobid: 0
    input: results/HG00733/align/aligned_tig_h1.bed.gz, temp/HG00733/lg_sv/batch_h1.tsv.gz, temp/HG00733/align/contigs_h1.fa.gz, temp/HG00733/align/contigs_h1.fa.gz.fai, data/ref/n_gap.bed.gz
    output: temp/HG00733/lg_sv/batch/sv_ins_h1_2.bed.gz, temp/HG00733/lg_sv/batch/sv_del_h1_2.bed.gz, temp/HG00733/lg_sv/batch/sv_inv_h1_2.bed.gz
    log: log/HG00733/lg_sv/log/lg_sv_h1_2.log (check log file(s) for error message)

RuleException:
RuntimeError in line 79 of /opt/pav/rules/call_lg.snakefile:
Received return code 1 from scripts/density.py for region chromosome14:94426-104523:
Traceback (most recent call last):
  File "/opt/pav/scripts/density.py", line 23, in <module>
    import pavlib
  File "/opt/pav/pavlib/__init__.py", line 3, in <module>
    from . import asmstat
  File "/opt/pav/pavlib/asmstat.py", line 10, in <module>
    import svpoplib
  File "/opt/pav/dep/svpop/svpoplib/__init__.py", line 4, in <module>
    from . import svmergeconfig
  File "/opt/pav/dep/svpop/svpoplib/svmergeconfig/__init__.py", line 3, in <module>
    from . import lexer
  File "/opt/pav/dep/svpop/svpoplib/svmergeconfig/lexer.py", line 1, in <module>
    import ply.lex
ModuleNotFoundError: No module named 'ply.lex'

[2022-12-12T161400.444674.snakemake.log](https://github.com/EichlerLab/pav/files/10209480/2022-12-12T161400.444674.snakemake.log)

**Comment by paudano** [comment]
I was able to find and fix this, thank you for the report and the stack trace. I'll be releasing an update shortly, I'll let you know when it's ready.

**Comment by paudano** [comment]
This should be fixed in 2.2.1, which is up now. The pipeline will pick up from where it failed. I am running a test now to confirm. Let me know if it succeeds or still fails.

**Comment by VLoegler** [comment]
I worked with my data, thanks a lot !
